# This file is part of gen-pkgs-all.

# gen-pkgs-all is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# gen-pkgs-all is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with gen-pkgs-all.  If not, see <https://www.gnu.org/licenses/>.


image: gentoo/stage3:amd64

pages:
  stage: deploy
  script:
  - mkdir -p /var/cache/binpkgs
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - mkdir -p /etc/portage/repos.conf
  - emerge-webrsync
  - export PORTAGE_BINHOST="https://xgqt.gitlab.io/gentoo-mini-mirror/binpkgs"
  - export FEATURES="getbinpkg"
  - export MAKEOPTS="--jobs=10"
  - export USE="-perl"
  - emerge -1nq --jobs=10 app-portage/gentoolkit app-eselect/eselect-repository dev-vcs/git sys-apps/busybox
  - time (sh ./gen-pkgs-all.sh)
  artifacts:
    paths:
    - public
  only:
  - master
